### ISSUE TITLE
Aggiungere aggiornamento della select a tutti i trigger di Gravity

### ISSUE THREAD

**Issue by adrianogiannacco** [Idearia/gf-time-conditional-field#2]
Viene ricaricata la select di default quando il Gravity Form si ricarica, ad esempio:
- se si tenta il Submit senza aver compilato tutti i campi obbligatori;
- se il form ha la paginazione e si torna indietro;
Si dovrebbe cambiare la select  non solo alla selezione della data ma anche a ogni trigger o aggiornamento di Gravity

**Comment by adrianogiannacco** [comment]
Forse bisogna aggiungere eventi e trigger laddove nel file assets/js/custom.js alla riga 10 c'è solo

```
// on datepicker change
$(config.datepickerId).change(function() {
```

**Comment by boghy933** [comment]
Problema risolto con l'ultimo commit 528a9fd1c72dea6d178b352807f8bd63ae94c310.
Adesso il field di tempo rimane con il valore impostato se un trigger di avanti/indietro e/o validation error viene chiamato.
